theme: jekyll-theme-tactile
title: Exploring Japan’s Restaurants
name: Lacee Xu
description: My friends will always ask me about food and restaurant recommendations for Japan since I lived in Tokyo for a couple of years and always loved the food and restaurant culture in Japan. 
It could be difficult to find a good restaurant in Japan as a visitor because most reviews and articles are written in Japanese. With this project, I’d like to provide useful information about where to find the best food in Japan through data visualization.
